controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

web_controller:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin

rest_controller:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api